# Generated by Django 6.0.2 on 2026-03-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
