# Generated by Django 6.0.2 on 2026-03-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
    ]
