# Generated by Django 6.0.2 on 2026-03-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review_create_date_review_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(default='This product quality is good'),
            preserve_default=False,
        ),
    ]
