# Generated by Django 6.0.2 on 2026-03-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_review_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
    ]
