# Generated by Django 6.0.2 on 2026-03-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
